# Stage 1: build static assets
FROM node:20 AS builder
WORKDIR /app

# Отключаем опциональные зависимости (npm не будет пытаться скачать native-модули)
ENV NPM_CONFIG_OPTIONAL=false

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: serve with nginx
FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
