version: '3.8'

services:
  frontend:
    container_name: react-frontend-round
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - VITE_KEYCLOAK_URL=http://keycloak:8080
      - VITE_KEYCLOAK_REALM=myrealm
      - VITE_KEYCLOAK_CLIENT_ID=myclient
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - keycloak-network

  backend:
    container_name: node-backend-round
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules # Исключаем node_modules из монтирования
    command: ["npx", "nodemon", "--legacy-watch", "index.js"] # Добавляем --legacy-watch
    networks:
      - keycloak-network

  # keycloak:
  #   container_name: keycloak-round
  #   image: quay.io/keycloak/keycloak:23.0.6
  #   command: start
  #   environment:
  #     - KC_HOSTNAME=localhost
  #     - KC_HOSTNAME_PORT=8080
  #     - KC_HOSTNAME_STRICT_BACKCHANNEL=false
  #     - KC_HOSTNAME_STRICT=false
  #     - KC_HTTP_ENABLED=true
  #     - KC_HOSTNAME_STRICT_HTTPS=false
  #     - KC_HEALTH_ENABLED=true
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - KC_DB=postgres
  #     - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
  #     - KC_DB_USERNAME=keycloak
  #     - KC_DB_PASSWORD=password
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - keycloak-network


  db:
    container_name: postgres-db-round
    image: postgres:16.2
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - '5438:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Монтируем наш скрипт и даём ему имя, чтобы Postgres выполнил его при инициализации
      - ./db/init/chesscup_init.sql:/docker-entrypoint-initdb.d/01-chesscup_init.sql:ro
    networks:
      - keycloak-network

volumes:
  node_modules:
    driver: local
  postgres-data:
    driver: local

networks:
  keycloak-network:
    driver: bridge

